### ISSUE TITLE
how this attention is different from attention described by Bahdanau?

### ISSUE THREAD

**Issue by shamanez** [ilivans/tf-rnn-attention#1]
I was mentioning this [paper](https://arxiv.org/abs/1409.0473)

**Comment by ilivans** [comment]
The authors of that paper solved translation task which is quite different from simple classification. There they used attention mechanism for every output token sequentially generating multiple context vectors, so that each output token depends on its context vector which is just linear combination of annotation vectors (hidden states) with specific weights. Whereas in classification task it's sufficient to use just one context vector because there is only one output corresponding to class, not a sequence (strictly saying the number of output neurons is equal to the number of classes, but nevertheless it's not a sequence and we can assume this is a single unit), so this is the main difference.
For the rest, this attention mechanism and "alignment model" from Bahdanau's paper are the same.

**Comment by Jiaxinl7** [comment]
If there is only one context vector (and it has nothing to do with other neighboring hidden states), how does it differ from adding one layer? @ilivans

**Comment by ilivans** [comment]
@Jiaxinl7 I suppose you mean adding a fully-connected layer, because attention layer is also one layer we add. In attention layer we take linear combination of hidden states as vectors. With a fully-connected layer you get a linear combination of single parameters, imagine you flatten all the hidden states and get one huge vector which you apply the dense layer to.

**Comment by Jiaxinl7** [comment]
@ilivans Thank you! So can I view this attention as a middle position between a fully-connected layer and mean over time (for this algorithm)?

**Comment by ilivans** [comment]
@Jiaxinl7 Almost. There is another significant difference between attention and fully-connected layers. In attention layer the coefficients are calculated during inference, for each input those are different (because we want to give more weight to specific tokens). In dense layer coefficients are constant because we don’t use positional information , we assume that incoming  neurons are somewhat independent.

**Comment by Jiaxinl7** [comment]
@ilivans I thought dense layer parameters could be trainable or untrainable, depending on the problem? (sometimes smaller learning rate?) Also I'm thinking about how this attention mechanism makes use of positional information, compared with the 'alignment' one used for machine translation. That one can look into the neighboring states, while this one is the same (after the training process) for different inputs. How does it know specific tokens usually appear in certain positions?

**Comment by ilivans** [comment]
@Jiaxinl7 Yes, I mean dense layer parameters are constant being trained unlike attention weights which are calculated for a given input individually.
Attention mechanism here works the same way as mentioned 'alignment' in MT, the only difference - it's applied once for single output instead of sequential outputs.
I'm sorry, "positional information" term is not the best choice probably here, what I wanted to say is that each state is weighted by relevance of the term in the corresponding position.

**Comment by Jiaxinl7** [comment]
@ilivans Thanks so much I got it :)
