### ISSUE TITLE
sentence and word ecnoder.

### ISSUE THREAD

**Issue by saxenarohit** [ilivans/tf-rnn-attention#13]
I can only see the word level encoder. Am I missing something? There should be two Bi-GRU layers right?

**Comment by ilivans** [comment]
Hi @saxenarohit ,
There is just one layer in the example, but multiple layers can be used with ease.
The encoder is word-level, indeed. What's wrong with that? The overall idea is to apply attention to specific words, so it makes sense to work on word level rather than character or sentence level (the last one is possible though for large texts)

**Comment by ilivans** [comment]
I see what you mean, it's not an exact implementation of an algorithm from "Hierarchical Attention Network". It's more simple example of attention use.
