### ISSUE TITLE
What the different between this project and the one below?

### ISSUE THREAD

**Issue by guotong1988** [ilivans/tf-rnn-attention#2]
https://github.com/pemywei/attention-nmt/blob/master/seq2seq.py#L121
The link project use prev_state as one of the input parameter.
@ilivans Thank you!!!

**Comment by ilivans** [comment]
The difference is the solved problem.
In the code you mentioned seq2seq model is used for Machine Translation problem and corresponding attention mechanism affects each of the output tokens separately. 
My repo proposes attention mechanism for different problem - classification. It works just with (bi)RNN rather than seq2seq model. There is only one output (predicted class), so mechanism applies once per input example (sample). 
Thank you for interest.
